config/routes.rb
Rails.application.routes.draw do

  root 'sessions#login'

  resources :users do
    get :search, on: :collection
    get :action_plan, on: :member
    resource :portfolio, only: [:edit, :update, :show], module: :users
    resources :resume_entries, except: [:new, :edit], module: :users
    resources :meetings, except: [:new, :edit], module: :users
    resources :goals, except: [:new, :edit], module: :users
    resources :action_items, only: [:index, :update], module: :users
    resources :klasses, path: :classes, only: [:index, :update], module: :users
    resources :feedbacks, module: :users
    resources :resources, module: :users do
      post :change_category, on: :collection
    end
    resources :projects, except: [:index], module: :users do
      get :tags, on: :collection
      get :download, on: :member
    end
  end

  resources :enrolls, only: [:create, :update, :destroy]

  resources :class_periods
  resources :klasses, path: :class

  namespace :admin do
    get :dashboard
  end

  resource :application_settings, only: [:show, :edit, :update], module: :admin

  get '/calendar', to: 'admin/application_settings#calendar'


  resources :parents, only: [:index, :create] do
    get :dashboard, on: :collection
  end

  namespace :project_attachments do
    get 'download/:id', action: :download
  end

  namespace :sessions, path: '/', as: nil do
    post :login_authentication
    get  :access_student
    get  :exit_student
    get  :login
    get  :logout
    get  :forgot_password
    post :forgot_password
  end

  get '/unfound', to: 'portfolios#unfound'
  get '/:username', to: 'portfolios#public'

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base

  belongs_to :user
  has_many :social_mediums, foreign_key: 'user_id'
  accepts_nested_attributes_for :social_mediums, allow_destroy: true

  validates :description, length: { maximum: 140, message: '140 character max' }

  has_attached_file :avatar,
                    default_url: -> (avatar) { ActionController::Base.helpers.asset_url('default-avatar.png') },
                    styles: { thumb: "100x100#", medium: '250x250#' }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_attached_file :background,
                    default_url: -> (background) { ActionController::Base.helpers.asset_path('tibetan-mountains.jpg') }
  validates_attachment_content_type :background, :content_type => /\Aimage\/.*\Z/

  def thumb_avatar_url
    avatar.url(:thumb)
  end
end

app/controllers/users/action_items_controller.rb
module Users
  class ActionItemsController < SessionsController
    load_and_authorize_resource :user
    authorize_resource :action_item, through: :user

    def index
      @incomplete = @user.admin_action_items.where(completed: [false, nil]).order(due_date: :asc)
      @complete = @user.admin_action_items.where(completed: true, archive: [false, nil]).order( updated_at: :desc)
      @action_items = @user.action_items.order(due_date: :asc).where(archive: [false, nil])
      @archived_action_items = @user.action_items.order(due_date: :asc).where(archive: true)
    end

    def update
      @action_item = ActionItem.find(params[:id])
      if @action_item.update(action_item_params)
        render json: {}, status: 200
      else
        render json: @action_item.errors, status: 422
      end
    end

    private

    def action_item_params
      params.require(:action_item).permit(
        :id,
        :due_date,
        :completed,
        :description,
        :user_id,
        :archive
      )
    end
  end
end

app/controllers/users/feedbacks_controller.rb
module Users
  class FeedbacksController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :feedback, through: :user

    def index
      @highlight_sidebar = 'Action Plan'
      @feedbacks = @feedbacks.order(created_at: :desc)
    end

    def create
      if @feedback.save
        redirect_to "#{action_plan_user_url(active_id)}#feedback"
      else
        render 'new'
      end
    end

    def new
      @highlight_sidebar = 'Action Plan'
    end

    def edit
      @highlight_sidebar = 'Action Plan'
    end

    def show
    end

    def update
      if @feedback.update(feedback_params)
        redirect_to "#{action_plan_user_url(active_id)}#feedback"
      else
        render 'edit'
      end
    end

    def destroy
      @feedback.destroy
      redirect_to "#{action_plan_user_url(active_id)}#feedback"
    end

    private

    def feedback_params
      params.require(:feedback).permit(
        :name,
        :text,
        :subject
      )
    end
  end
end

app/controllers/users/goals_controller.rb
module Users
  class GoalsController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :goal, through: :user

    def index
      @goals = @goals.includes(:action_items, :user)
    end

    def create
      if @goal.save
        render :show, status: 201
      else
        render json: @goal.errors, status: 422
      end
    end

    def show
    end

    def update
      if @goal.update(goal_params)
        render :show, status: 200
      else
        render json: @goal.errors, status: 422
      end
    end

    def destroy
      @goal.destroy
      head :no_content
    end

    private

    def goal_params
      params.require(:goal).permit(
        :title,
        :description,
        :is_completed,
        :due_date,
        :user_id,
        action_items_attributes: [
          :description,
          :due_date,
          :id,
          :_destroy
        ]
      )
    end
  end
end

app/controllers/users/klasses_controller.rb
module Users
  class KlassesController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :klass, through: :user, except: [:update]

    def index
      @highlight_sidebar = 'Dashboard'
      @klasses = @user.uncompleted_klasses if params[:current].present?
      @klasses = @user.completed_klasses if params[:past].present?
      @klasses = @klasses.includes(:enrolls)
    end

    def update
      @klass = Klass.find(params[:id])
      if @klass.update(klass_params)
        @klasses = @user.klasses
        render json: {}, status: 200
      else
        render json: @klass.errors, status: 422
      end
    end

    private

    def klass_params
      params.require(:klass).permit(
        :name,
        :description,
        :time,
        :instructor,
        :instructor_email,
        :instructor_phone,
        :location,
        :one_on_one,
        :google_drive_url,
        enrolls_attributes: [
          :id,
          :user_id,
          :completed,
          :_destroy
        ]
      )
    end

  end

end

app/controllers/users/meetings_controller.rb
module Users
  class MeetingsController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :meeting, through: :user

    def index
      @meetings = @meetings.where(draft: false).includes(:action_items, :user)
    end

    def create
      if @meeting.save
        render :show, status: 201
      else
        render json: @meeting.errors, status: 422
      end
    end

    def show; end

    def update
      if @meeting.update(meeting_params)
        render :show, status: 200
      else
        render json: @meeting.errors, status: 422
      end
    end

    def destroy
      @meeting.destroy
      head :no_content
    end

    private

    def meeting_params
      params.require(:meeting).permit(
        :notes,
        :user_id,
        :draft,
        action_items_attributes: [
          :id,
          :description,
          :due_date,
          :user_id,
          :completed,
          :_destroy
        ]
      )
    end
  end
end

app/controllers/users/portfolios_controller.rb
module Users
  class PortfoliosController < ApplicationController
    load_and_authorize_resource :user
    load_and_authorize_resource :portfolio, through: :user, :singleton => true, except: [:public, :unfound]

    def show
      render layout: 'public' if current_user != @user && session[:student_id].blank?
    end

    def edit
    end

    def update
      if @portfolio.update(portfolio_params)
        redirect_to user_portfolio_path(@user), notice: 'Portfolio updated successfully!'
      else
        flash.now[:alert] = 'Failed to updated portfolio'
        render :edit
      end
    end

    def public
      @user = User.joins(:portfolio).find_by(portfolios: { private: [nil, false] }, username: params[:username])
      if @user
        @portfolio = @user.portfolio
        render action: :show, layout: 'public'
      else
        redirect_to action: :unfound, params: { username: params[:username] }
      end
    end

    def unfound
      render layout: 'public'
    end

    private

    def portfolio_params
      params.require(:portfolio).permit(
        :avatar,
        :background,
        :description,
        :color,
        :private,
        social_mediums_attributes: [
          :link,
          :name,
          :_destroy,
          :id
        ]
      )
    end
  end
end

app/controllers/users/projects_controller.rb
module Users
  class ProjectsController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :project, through: :user
    before_action :set_sidebar_highlight

    def new
      @project.tags.build
    end

    def create
      if @project.save
        redirect_to [@user, @project], flash: { notice: 'Project successfully created!' }
      else
        flash.now[:alert] = 'Could not create your project, some fields may have been missing!'
        render :new
      end
    end

    def update
      if @project.update(project_params)
        redirect_to [@user, @project], flash: { notice: 'Project updated!' }
      else
        flash.now[:alert] = 'Project could not be updated.'
        render :edit
      end
    end

    def tags
      @tags = @user.tags
      @tags = @tags.where('name like ?', "%#{params[:q]}%") if params[:q].present?
    end

    def edit; end

    def show
      render layout: 'public'
    end

    def download
      redirect_to @project.download_url
    end

    def destroy
      @project.destroy
      redirect_to user_portfolio_path(@user), flash: { notice: 'Portfolio piece deleted' }
    end

    private

    def set_sidebar_highlight
      @highlight_sidebar = 'Portfolio'
    end

    def project_params
      params.require(:project).permit(
        :title,
        :description,
        :link,
        :priority,
        :document,
        :body,
        :photo,
        :location,
        :date_completed,
        tags_attributes: [
          :name,
          :_destroy,
          :id
        ]
      )
    end
  end
end

app/controllers/users/resources_controller.rb
module Users
  class ResourcesController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :resource, through: :user

    def index
      @resources = @user.resources.where(general: [nil, false]).group_by(&:category)
      @general_resources = Resource.where(general: true).group_by(&:category)

      respond_to do |format|
        format.html
        format.json { render json: { general_resources: @general_resources, resources: @resources } }
      end
    end

    def new
      params[:general].nil? ? @highlight_sidebar = 'Resources' : @highlight_sidebar = 'Dashboard'
    end

    def create
      if @resource.save
        redirect_to user_resources_path(@user), flash: { notice: 'Resource created successfully!' }
      else
        render :new
      end
    end

    def update
      if @resource.update(resource_params)
        redirect_to user_resources_path(@user), flash: { notice: 'Resource updated successfully!' }
      else
        flash.now[:alert] = 'Failed to update resource.'
        render :edit
      end
    end

    def change_category
      resources = Resource.where(category: params[:old_category])
      resources.update_all({ category: params[:new_category] })
      render json: { category: params[:new_category] }
    end

    def edit
      @highlight_sidebar = 'Resources'
    end

    def show
    end

    def destroy
      @resource.destroy
      respond_to do |format|
        format.html { redirect_to user_resources_path(@user), flash: { notice: "Resource successfully deleted" } }
        format.json { head :no_content }
      end
    end

    private

      def resource_params
        params.require(:resource).permit(
          :link,
          :category,
          :title,
          :description,
          :general
        )
      end
    end
end

app/controllers/users/resume_entries_controller.rb
module Users
  class ResumeEntriesController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :resume_entry, through: :user

    def index
    end

    def create
      if @resume_entry.save
        render :show, status: 201
      else
        render json: @resume_entry.errors, status: 422
      end
    end

    def show
    end

    def update
      if @resume_entry.update(resume_entry_params)
        render :show, status: 200
      else
        render json: @resume_entry.errors, status: 422
      end
    end

    def destroy
      @resume_entry.destroy
      head :no_content
    end

    private

    def resume_entry_params
      params.require(:resume_entry).permit(
        :id,
        :title,
        :subtitle,
        :description,
        :date
      )
    end
  end
end

app/controllers/users_controller.rb
class UsersController < SessionsController
  load_and_authorize_resource

  def index
    @users = @users.students
    @highlight_sidebar = 'Dashboard'
    @users = @users.default_search(params[:q]) if params[:q].present?
    @users = @users.reorder('archive asc, first_name asc')
    respond_to do |format|
      format.json
      format.html
    end
  end

  def action_plan
    @highlight_sidebar = 'Action Plan'
    @draft_meeting = active_user.meetings.where(draft: true).first
  end

  def show
  end

  def new
    @highlight_sidebar = 'Dashboard'
  end

  def edit
    @highlight_sidebar = 'Dashboard'
  end

  def create
    if @user.save
      @user.children.create(student_id: params[:user][:student_id]) if @user.parent?
      redirect_to redirect_to_path, notice: "#{@user.role.capitalize} account successfully created."
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params.except(:password, :password_confirmation))
          @user.pword = params[:user][:password] if params[:user][:password].present?
          @user.save
          format.html { redirect_to redirect_to_path, flash: { notice: 'Account successfully updated!' } }
          format.json { render :show }
      else
        @highlight_sidebar = 'Dashboard'
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    name = @user.full_name.capitalize
    @user.destroy
    respond_to do |format|
      format.html { redirect_to redirect_to_path, flash: { notice: "#{name} account was successfully deleted." } }
      format.json { head :no_content }
    end
  end

  private

    def redirect_to_path
      return admin_dashboard_path if @user.admin?
      return users_path if @user.parent? || @user.student?
    end

    def user_params
      @user_params ||= params.require(:user).permit(
        :first_name,
        :last_name,
        :meeting_time,
        :role,
        :email,
        :password,
        :password_confirmation,
        :username,
        :archive,
        social_mediums_attributes: [
          :link,
          :name,
          :_destroy,
          :id
        ]
      )
    end

end

app/views/users/portfolios/edit.html.erb
<nav>
  <div class='nav-wrapper'>
    <%= link_to 'Portfolio', user_portfolio_path, class: 'breadcrumb' %>
    <span class='breadcrumb'>Edit Portfolio</span>
  </div>
</nav>

<section  class='section-container'>
  <%= form_for [@user, @portfolio], html: { class: 'edit-student' } do |f| %>
    <div class='row'>
      <div class='col s12 m4'>
        <div class='avatar-column'>
          <%= image_tag @portfolio.avatar.url, class: 'edit-avatar' %>
        </div>

        <label class='custom-file-upload waves-effect waves-light btn'>
          <%= f.file_field :avatar %>
          <%= fa_icon 'camera', text: 'CHANGE' %>
        </label>
      </div>

      <div class='col s12 m8'>
        <div class='row'>
          <div class='input-field col s12'>
            <%= f.text_area :description, placeholder: '140 characters maximum', length: '140', class: 'materialize-textarea'  %>
            <%= f.label :description, 'SHORT BIO' %>
          </div>
        </div>

        <div class='row'>
          <div class='col s12'>
            <%= f.label :color %><br/><br/>
            <%= color_field(:portfolio, :color) %>
          </div>
        </div>

        <div class='row'>
          <div class='file-field input-field col s12'>
            <div class='btn'>
              <span>Background</span>
              <%= f.file_field :background %>
            </div>
            <div class='file-path-wrapper'>
              <input class='file-path' type='text'
              placeholder='Upload backgroung image' value='<%= @portfolio.background.original_filename %>'>
            </div>
          </div>
        </div>

        <div class='row'>
          <div class='switch col s12'>
            <label style='font-size: 1rem; margin-bottom: 15px; display: block;'>Make portfolio private</label>
            <%= f.label :private do %>
            No
            <%= f.check_box :private %>
            <span class='lever'></span>
            Yes
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class='row'>
      <div class='col s12 m8 offset-m4'>
        <div class='row'>
          <h5 class='col s12'>You on the web</h5>
        </div>

        <%= f.nested_fields_for :social_mediums do |ff| %>
        <div class='row'>
          <div class='input-field col s12 m5'>
            <%= ff.url_field :link %>
            <%= ff.label :link, 'LINK' %>
          </div>
          <div class='input-field col s12 m6'>
            <%= ff.text_field :name %>
            <%= ff.label :name, 'SHORT TITLE'%>
          </div>
          <div class='input-field col s12 m1'>
            <%= ff.remove_nested_fields_link fa_icon('trash-o', class: 'no-padding'),
            class: 'red-text' %>
          </div>
        </div>
        <% end %>
        <div class='row'>
          <div class='col s12'>
            <%= f.add_nested_fields_link :social_mediums, fa_icon('plus-circle', text: 'Add Link'), class: 'waves-effect waves-light btn' %>
          </div>
        </div>

        <div class='row'>
          <div class='col s12'>
            <%= f.button 'Save', class: 'waves-effect waves-light btn' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</section>

app/views/users/portfolios/show.html.erb
<div class='portfolio'>
  <div class='info'>
    <div class='header-bg' style=<%= "background-image:url(#{@portfolio.background.url})" unless @portfolio.background.blank? %>>
      <%= link_to fa_icon('cog', text: 'Edit', right: true), edit_user_portfolio_path(@user), class: 'student-edit' if can?(:edit, @portfolio) %>
      <div class='dark-overlay'>
      <div class='header-container'>

          <div class='row'>
            <div class='col s6 m3 l3'>
              <div class='student-avatar'>
                <%= image_tag @portfolio.avatar.url(:medium), class: 'responsive-img', style: "border-color: #{@portfolio.color}" %>
              </div>
            </div>

            <div class='col s6 m9 l9'>
              <div class='row'>
                <div class='col s12'>
                  <h2 class='center-align'><%= @user.full_name %></h2>
                </div>
                <div class='col s12 hide-on-small-only'>
                  <div class='white-text thin med-opacity center-align description'><%= @portfolio.description %></div>
                </div>
              </div>
              <div class='social-media row hide-on-small-only'>
                <% @portfolio.social_mediums.first(3).each do |sm| %>
                    <div class='item white-text thin med-opacity'>
                      <%= link_to sm.link, target: '_blank', title: sm.name do %>
                        <%= fa_icon(sm.icon) %> <br/><%= sm.name %>
                      <% end %>
                    </div>
                <% end %>
              </div>
            </div>
          </div>

            <div class='social-media row hide-on-med-and-up'>
              <% @portfolio.social_mediums.first(3).each do |sm| %>
                <div class='col s4 center-align'>
                  <span class='white-text thin med-opacity truncate'>
                    <%= link_to fa_icon(sm.icon), sm.link, title: sm.name %>
                  </span>
                </div>
              <% end %>
            </div>

        </div>
        </div>
      </div>
    </div>
  </div>

  <div class='row z-depth-1'>
    <ul class='tabs'>
      <li class='tab col s6'><a href='#portfolio'>Portfolio</a></li>
      <li class='tab col s6'><a href='#resume'>Resume</a></li>
    </ul>
  </div>
  <div class='projects-and-resume'>
    <div id='portfolio' class='section-container'>
      <% if cannot?(:edit, @portfolio) && @user.projects.size == 0 %>
        <h4 class='center-align'><%= @user.full_name %> has not created any projects yet.</h4>
      <% end %>

      <div id='portfolio-piece-grid' data-columns class='row'>
        <% if can? :edit, @portfolio %>
        <div class='col s12'>
          <div class='card-panel project-wrapper hoverable' style='border-color: <%= @portfolio.color %>'>
            <div class='card-content'>
              <%= link_to '', new_user_project_path(@user), class: 'project-link' %>
              <div class='add-project'>
                <%= link_to fa_icon('plus-circle', style: "color: #{@portfolio.color}"), new_user_project_path(@user) %>
                <br><br>Add portfolio piece
              </div>
            </div>
          </div>
        </div>
        <% end %>

        <% @user.projects.each do |project| %>
          <div class='col s12'>
            <div class='card project-wrapper hoverable' style='border-color: <%= @portfolio.color %>'>
              <div class='card-image'>
                <%= image_tag project.photo if project.photo.present? %>
              </div>
              <div class='card-content'>
                <span class='card-title black-text truncate'><%= project.title %></span>

                <p class='grey-text text-darken-1'>
                <%= project.description %>
                </p>
              </div>
              <%= link_to '', [@user, project], class: 'project-link', title: project.title %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div id='resume' class='section-container'>
      <%= react_component 'ResumeEntries', { user_id: @user.id, editable: can?(:edit, @portfolio) } %>
    </div>
  </div>
</div>

app/views/users/portfolios/unfound.html.erb
<div class='unfound center-align'>
  <div class='icons'>
    <i class='material-icons'>search</i>
    <i class='material-icons close'>close</i>
    <i class='material-icons'>people</i>
  </div>
  <h4>We couldn't find a student with the username: <i><%= params[:username] %></i></h4>
  <a class='btn teal lighten-2' href=<%= "mailto:#{ENV['EMAIL']}" %> target="_top">Need help?</a>
</div>