config/routes.rb
Rails.application.routes.draw do

  root 'sessions#login'

  resources :users do
    get :search, on: :collection
    get :action_plan, on: :member
    resource :portfolio, only: [:edit, :update, :show], module: :users
    resources :resume_entries, except: [:new, :edit], module: :users
    resources :meetings, except: [:new, :edit], module: :users
    resources :goals, except: [:new, :edit], module: :users
    resources :action_items, only: [:index, :update], module: :users
    resources :klasses, path: :classes, only: [:index, :update], module: :users
    resources :feedbacks, module: :users
    resources :resources, module: :users do
      post :change_category, on: :collection
    end
    resources :projects, except: [:index], module: :users do
      get :tags, on: :collection
      get :download, on: :member
    end
  end

  resources :enrolls, only: [:create, :update, :destroy]

  resources :class_periods
  resources :klasses, path: :class

  namespace :admin do
    get :dashboard
  end

  resource :application_settings, only: [:show, :edit, :update], module: :admin

  get '/calendar', to: 'admin/application_settings#calendar'


  resources :parents, only: [:index, :create] do
    get :dashboard, on: :collection
  end

  namespace :project_attachments do
    get 'download/:id', action: :download
  end

  namespace :sessions, path: '/', as: nil do
    post :login_authentication
    get  :access_student
    get  :exit_student
    get  :login
    get  :logout
    get  :forgot_password
    post :forgot_password
  end

  get '/unfound', to: 'portfolios#unfound'
  get '/:username', to: 'portfolios#public'

end

app/models/project.rb
class Project < ActiveRecord::Base

	default_scope { order(priority: :desc, date_completed: :desc) }

  belongs_to :user
  has_many :tags, dependent: :destroy
  accepts_nested_attributes_for :tags, allow_destroy: true

  has_attached_file :photo, :default_url => 'blue-space-cloud.jpg'
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  has_attached_file :document
  validates_attachment_size :document, less_than: 25.megabytes
  do_not_validate_attachment_file_type :document

  validates :title, presence: { message: 'Title is required' }
  validates :description, length: { maximum: 200, too_long: '%{count} characters is the maximum allowed' }

  def download_url
    s3 = AWS::S3.new.buckets[ENV['S3_BUCKET_NAME']]
    s3.objects[ self.document.path[1..-1] ].url_for( :read,
      expires_in: 60.minutes,
      use_ssl:    true,
      response_content_disposition: "attachment; filename=\"#{document.original_filename}\"" ).to_s
  end

  def next
    ids = Project.where(user_id: self.user_id).pluck :id
    pos = ids.index(self.id)
    next_pos = ids[ (pos + 1) % ids.length ]
    Project.find next_pos
  end

  def previous
    ids = Project.where(user_id: self.user_id).pluck :id
    pos = ids.index(self.id)
    prev_pos = ids[ (pos - 1) % ids.length ]
    Project.find prev_pos
  end

  before_save do
    self.date_completed = created_at if date_completed.blank?
  end

end

app/controllers/users/action_items_controller.rb
module Users
  class ActionItemsController < SessionsController
    load_and_authorize_resource :user
    authorize_resource :action_item, through: :user

    def index
      @incomplete = @user.admin_action_items.where(completed: [false, nil]).order(due_date: :asc)
      @complete = @user.admin_action_items.where(completed: true, archive: [false, nil]).order( updated_at: :desc)
      @action_items = @user.action_items.order(due_date: :asc).where(archive: [false, nil])
      @archived_action_items = @user.action_items.order(due_date: :asc).where(archive: true)
    end

    def update
      @action_item = ActionItem.find(params[:id])
      if @action_item.update(action_item_params)
        render json: {}, status: 200
      else
        render json: @action_item.errors, status: 422
      end
    end

    private

    def action_item_params
      params.require(:action_item).permit(
        :id,
        :due_date,
        :completed,
        :description,
        :user_id,
        :archive
      )
    end
  end
end

app/controllers/users/feedbacks_controller.rb
module Users
  class FeedbacksController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :feedback, through: :user

    def index
      @highlight_sidebar = 'Action Plan'
      @feedbacks = @feedbacks.order(created_at: :desc)
    end

    def create
      if @feedback.save
        redirect_to "#{action_plan_user_url(active_id)}#feedback"
      else
        render 'new'
      end
    end

    def new
      @highlight_sidebar = 'Action Plan'
    end

    def edit
      @highlight_sidebar = 'Action Plan'
    end

    def show
    end

    def update
      if @feedback.update(feedback_params)
        redirect_to "#{action_plan_user_url(active_id)}#feedback"
      else
        render 'edit'
      end
    end

    def destroy
      @feedback.destroy
      redirect_to "#{action_plan_user_url(active_id)}#feedback"
    end

    private

    def feedback_params
      params.require(:feedback).permit(
        :name,
        :text,
        :subject
      )
    end
  end
end

app/controllers/users/goals_controller.rb
module Users
  class GoalsController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :goal, through: :user

    def index
      @goals = @goals.includes(:action_items, :user)
    end

    def create
      if @goal.save
        render :show, status: 201
      else
        render json: @goal.errors, status: 422
      end
    end

    def show
    end

    def update
      if @goal.update(goal_params)
        render :show, status: 200
      else
        render json: @goal.errors, status: 422
      end
    end

    def destroy
      @goal.destroy
      head :no_content
    end

    private

    def goal_params
      params.require(:goal).permit(
        :title,
        :description,
        :is_completed,
        :due_date,
        :user_id,
        action_items_attributes: [
          :description,
          :due_date,
          :id,
          :_destroy
        ]
      )
    end
  end
end

app/controllers/users/klasses_controller.rb
module Users
  class KlassesController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :klass, through: :user, except: [:update]

    def index
      @highlight_sidebar = 'Dashboard'
      @klasses = @user.uncompleted_klasses if params[:current].present?
      @klasses = @user.completed_klasses if params[:past].present?
      @klasses = @klasses.includes(:enrolls)
    end

    def update
      @klass = Klass.find(params[:id])
      if @klass.update(klass_params)
        @klasses = @user.klasses
        render json: {}, status: 200
      else
        render json: @klass.errors, status: 422
      end
    end

    private

    def klass_params
      params.require(:klass).permit(
        :name,
        :description,
        :time,
        :instructor,
        :instructor_email,
        :instructor_phone,
        :location,
        :one_on_one,
        :google_drive_url,
        enrolls_attributes: [
          :id,
          :user_id,
          :completed,
          :_destroy
        ]
      )
    end

  end

end

app/controllers/users/meetings_controller.rb
module Users
  class MeetingsController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :meeting, through: :user

    def index
      @meetings = @meetings.where(draft: false).includes(:action_items, :user)
    end

    def create
      if @meeting.save
        render :show, status: 201
      else
        render json: @meeting.errors, status: 422
      end
    end

    def show; end

    def update
      if @meeting.update(meeting_params)
        render :show, status: 200
      else
        render json: @meeting.errors, status: 422
      end
    end

    def destroy
      @meeting.destroy
      head :no_content
    end

    private

    def meeting_params
      params.require(:meeting).permit(
        :notes,
        :user_id,
        :draft,
        action_items_attributes: [
          :id,
          :description,
          :due_date,
          :user_id,
          :completed,
          :_destroy
        ]
      )
    end
  end
end

app/controllers/users/portfolios_controller.rb
module Users
  class PortfoliosController < ApplicationController
    load_and_authorize_resource :user
    load_and_authorize_resource :portfolio, through: :user, :singleton => true, except: [:public, :unfound]

    def show
      render layout: 'public' if current_user != @user && session[:student_id].blank?
    end

    def edit
    end

    def update
      if @portfolio.update(portfolio_params)
        redirect_to user_portfolio_path(@user), notice: 'Portfolio updated successfully!'
      else
        flash.now[:alert] = 'Failed to updated portfolio'
        render :edit
      end
    end

    def public
      @user = User.joins(:portfolio).find_by(portfolios: { private: [nil, false] }, username: params[:username])
      if @user
        @portfolio = @user.portfolio
        render action: :show, layout: 'public'
      else
        redirect_to action: :unfound, params: { username: params[:username] }
      end
    end

    def unfound
      render layout: 'public'
    end

    private

    def portfolio_params
      params.require(:portfolio).permit(
        :avatar,
        :background,
        :description,
        :color,
        :private,
        social_mediums_attributes: [
          :link,
          :name,
          :_destroy,
          :id
        ]
      )
    end
  end
end

app/controllers/users/projects_controller.rb
module Users
  class ProjectsController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :project, through: :user
    before_action :set_sidebar_highlight

    def new
      @project.tags.build
    end

    def create
      if @project.save
        redirect_to [@user, @project], flash: { notice: 'Project successfully created!' }
      else
        flash.now[:alert] = 'Could not create your project, some fields may have been missing!'
        render :new
      end
    end

    def update
      if @project.update(project_params)
        redirect_to [@user, @project], flash: { notice: 'Project updated!' }
      else
        flash.now[:alert] = 'Project could not be updated.'
        render :edit
      end
    end

    def tags
      @tags = @user.tags
      @tags = @tags.where('name like ?', "%#{params[:q]}%") if params[:q].present?
    end

    def edit; end

    def show
      render layout: 'public'
    end

    def download
      redirect_to @project.download_url
    end

    def destroy
      @project.destroy
      redirect_to user_portfolio_path(@user), flash: { notice: 'Portfolio piece deleted' }
    end

    private

    def set_sidebar_highlight
      @highlight_sidebar = 'Portfolio'
    end

    def project_params
      params.require(:project).permit(
        :title,
        :description,
        :link,
        :priority,
        :document,
        :body,
        :photo,
        :location,
        :date_completed,
        tags_attributes: [
          :name,
          :_destroy,
          :id
        ]
      )
    end
  end
end

app/controllers/users/resources_controller.rb
module Users
  class ResourcesController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :resource, through: :user

    def index
      @resources = @user.resources.where(general: [nil, false]).group_by(&:category)
      @general_resources = Resource.where(general: true).group_by(&:category)

      respond_to do |format|
        format.html
        format.json { render json: { general_resources: @general_resources, resources: @resources } }
      end
    end

    def new
      params[:general].nil? ? @highlight_sidebar = 'Resources' : @highlight_sidebar = 'Dashboard'
    end

    def create
      if @resource.save
        redirect_to user_resources_path(@user), flash: { notice: 'Resource created successfully!' }
      else
        render :new
      end
    end

    def update
      if @resource.update(resource_params)
        redirect_to user_resources_path(@user), flash: { notice: 'Resource updated successfully!' }
      else
        flash.now[:alert] = 'Failed to update resource.'
        render :edit
      end
    end

    def change_category
      resources = Resource.where(category: params[:old_category])
      resources.update_all({ category: params[:new_category] })
      render json: { category: params[:new_category] }
    end

    def edit
      @highlight_sidebar = 'Resources'
    end

    def show
    end

    def destroy
      @resource.destroy
      respond_to do |format|
        format.html { redirect_to user_resources_path(@user), flash: { notice: "Resource successfully deleted" } }
        format.json { head :no_content }
      end
    end

    private

      def resource_params
        params.require(:resource).permit(
          :link,
          :category,
          :title,
          :description,
          :general
        )
      end
    end
end

app/controllers/users/resume_entries_controller.rb
module Users
  class ResumeEntriesController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :resume_entry, through: :user

    def index
    end

    def create
      if @resume_entry.save
        render :show, status: 201
      else
        render json: @resume_entry.errors, status: 422
      end
    end

    def show
    end

    def update
      if @resume_entry.update(resume_entry_params)
        render :show, status: 200
      else
        render json: @resume_entry.errors, status: 422
      end
    end

    def destroy
      @resume_entry.destroy
      head :no_content
    end

    private

    def resume_entry_params
      params.require(:resume_entry).permit(
        :id,
        :title,
        :subtitle,
        :description,
        :date
      )
    end
  end
end

app/controllers/users_controller.rb
class UsersController < SessionsController
  load_and_authorize_resource

  def index
    @users = @users.students
    @highlight_sidebar = 'Dashboard'
    @users = @users.default_search(params[:q]) if params[:q].present?
    @users = @users.reorder('archive asc, first_name asc')
    respond_to do |format|
      format.json
      format.html
    end
  end

  def action_plan
    @highlight_sidebar = 'Action Plan'
    @draft_meeting = active_user.meetings.where(draft: true).first
  end

  def show
  end

  def new
    @highlight_sidebar = 'Dashboard'
  end

  def edit
    @highlight_sidebar = 'Dashboard'
  end

  def create
    if @user.save
      @user.children.create(student_id: params[:user][:student_id]) if @user.parent?
      redirect_to redirect_to_path, notice: "#{@user.role.capitalize} account successfully created."
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params.except(:password, :password_confirmation))
          @user.pword = params[:user][:password] if params[:user][:password].present?
          @user.save
          format.html { redirect_to redirect_to_path, flash: { notice: 'Account successfully updated!' } }
          format.json { render :show }
      else
        @highlight_sidebar = 'Dashboard'
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    name = @user.full_name.capitalize
    @user.destroy
    respond_to do |format|
      format.html { redirect_to redirect_to_path, flash: { notice: "#{name} account was successfully deleted." } }
      format.json { head :no_content }
    end
  end

  private

    def redirect_to_path
      return admin_dashboard_path if @user.admin?
      return users_path if @user.parent? || @user.student?
    end

    def user_params
      @user_params ||= params.require(:user).permit(
        :first_name,
        :last_name,
        :meeting_time,
        :role,
        :email,
        :password,
        :password_confirmation,
        :username,
        :archive,
        social_mediums_attributes: [
          :link,
          :name,
          :_destroy,
          :id
        ]
      )
    end

end

app/views/users/projects/_form.html.erb
<% date_completed = @project.date_completed.strftime('%d %B, %Y') if @project.date_completed.present? %>

<%= form_for [@user, @project], html: { class: 'one-page', multipart: true } do |f| %>

  <div class='row'>
    <div class='input-field col s12 m6'>
      <%= f.text_field :title %>
      <%= f.label :title %>
    </div>
    <div class='input-field col s12 m6'>
      <%= f.text_field :date_completed, value: date_completed, class: 'datepicker' %>
      <%= f.label :date_completed %>
    </div>
  </div>

  <div class='row'>
    <div class='input-field col s12'>
    <%= f.text_area :description, length: '200', class: 'materialize-textarea' %>
    <%= f.label :description, 'Brief Description' %>
    </div>
  </div>

  <div class='row'>
    <div class='input-field col s12'>
    <%= f.text_area :body, placeholder: 'Write whatever you want here?', class: 'tinymce' %>
      </div>
  </div>

  <div class='row'>
    <div class='input-field col s12 tagger'>
      <%= text_field_tag :tag, nil, class: 'tag', placeholder: 'Enter tag and press enter' %>
      <%= label_tag :tag %>
      <ul class='autocomplete-dropdown'>
      </ul>
      <div class='tag-container'>
        <!-- This is here just to initiate tags. -->
        <%= f.fields_for :tags do |ff| %>
          <% next if ff.object.new_record? %>
          <div class='chip chip-tag' data-index='<%= ff.index %>'>
            <%= ff.object.name %>
            <i class='fa fa-times'></i>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='file-field input-field col s12'>
      <div class='btn'>
        <span>Display Photo</span>
        <%= f.file_field :photo %>
      </div>
      <div class='file-path-wrapper'>
        <input class='file-path' type='text'
          placeholder='Upload one photo' value='<%= @project.photo.original_filename %>'>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='file-field input-field col s12'>
      <div class='btn'>
        <span>ATTACHMENT</span>
        <%= f.file_field :document %>
      </div>
      <div class='file-path-wrapper'>
        <input class='file-path' type='text'
          placeholder='Upload a document' value='<%= @project.document.original_filename %>'>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='switch col s12 m9 l5'>
      <%= f.label :priority do %>
        Normal
        <%= f.check_box :priority %>
        <span class='lever'></span>
        High
      <% end %>
    </div>
  </div>

  <div class='row'>
    <div class='col s12'>
      <%= f.button 'Save', class: 'waves-effect waves-light btn' %>
      <%= link_to 'Delete', [@user, @project], method: :delete, data: { confirm: 'Are you positive that you want to delete this project?' }, class: 'waves-effect waves-light btn red darken-2' unless @project.new_record? %>
    </div>
  </div>
<% end %>

app/views/users/projects/edit.html.erb
<nav>
  <div class='nav-wrapper'>
    <%= link_to 'Portfolio', user_portfolio_path, class: 'breadcrumb' %>
    <span class='breadcrumb'>Edit Portfolio Piece</span>
  </div>
</nav>

<section class='section-container'>
  <div class='row'>
    <h4>Edit Portfolio Piece</h4>
  </div>
  <%= render 'form' %>
</section>

app/views/users/projects/new.html.erb
<nav>
  <div class='nav-wrapper'>
    <%= link_to 'Portfolio', user_portfolio_path, class: 'breadcrumb' %>
    <span class='breadcrumb'>New Portfolio Piece</span>
  </div>
</nav>

<section class='section-container'>
  <div class='row'>
    <h4>New Portfolio Piece</h4>
  </div>
  <%= render 'form' %>
</section>

app/views/users/projects/show.html.erb
<section class='section-container no-padding project-show'>
    <% if @user.projects.size > 1 %>
    <div class='hide-on-small-only project-nav left-arrow'>
      <%= link_to fa_icon('angle-left'), [@user, @project.previous], class: 'nav-left' %>
    </div>
    <% end %>

    <div class='project-content'>
      <div class='thin-container'>

        <div class='menu'></div>

        <%= link_to fa_icon('pencil'), edit_user_project_path(user_id: @user.id, id: @project.id),
          class: 'btn-floating btn-large waves-effect waves-light right', style: "background-color: #{@project.user.portfolio.color}" if can?(:edit, @project) %>

        <%= link_to fa_icon('th'), user_portfolio_path(@user),
          class: 'btn-floating btn-large waves-effect waves-light left', style: "background-color: #{@project.user.portfolio.color}" %>

        <h1 class='center-align thick'><%= @project.title %></h1>

        <hr>

        <div class='center-align thin' style='color: <%= @project.user.portfolio.color %>'>
          <%= @project.date_completed.strftime('%B %d, %Y / ') if @project.date_completed.present? %>
          <%= "By <span class='normal'>#{@project.user.full_name}</span>".html_safe %>
        </div>

        <div class='show-tag center-align thin text-darken-1 '>
          <% @project.tags.each do |tag| %>
            <div class='chip'>
              <span><%= tag.name %></span>
            </div>
          <% end %>
        </div>

        <br>

        <div class='flow-text center-align'><%= @project.description %></div>

        <% if @project.photo.present? %>
          <div class='show-display-image'>
            <%= image_tag @project.photo.url, class: 'responsive-img materialboxed' %>
          </div>
        <% end %>

        <div class='project-body'>
        <%= @project.body.html_safe %>
        </div>

        <% if @project.document.present? %>
          <h6 class='bold'>Attachment</h6>
            <ul>
              <li><%= link_to @project.document.original_filename, download_user_project_path(user_id: @user.id, id: @project.id) %></li>
            </ul>
        <% end %>

        <br/>
        <br/>
      </div>
    </div>

    <% if @user.projects.size > 1 %>
      <div class='hide-on-small-only project-nav right-arrow'>
        <%= link_to fa_icon('angle-right'), [@user, @project.next], class: 'nav-right' %>
      </div>
    <% end %>
  </div>
</section>