config/routes.rb
Rails.application.routes.draw do

  root 'sessions#login'

  resources :users do
    get :search, on: :collection
    get :action_plan, on: :member
    resource :portfolio, only: [:edit, :update, :show], module: :users
    resources :resume_entries, except: [:new, :edit], module: :users
    resources :meetings, except: [:new, :edit], module: :users
    resources :goals, except: [:new, :edit], module: :users
    resources :action_items, only: [:index, :update], module: :users
    resources :klasses, path: :classes, only: [:index, :update], module: :users
    resources :feedbacks, module: :users
    resources :resources, module: :users do
      post :change_category, on: :collection
    end
    resources :projects, except: [:index], module: :users do
      get :tags, on: :collection
      get :download, on: :member
    end
  end

  resources :enrolls, only: [:create, :update, :destroy]

  resources :class_periods
  resources :klasses, path: :class

  namespace :admin do
    get :dashboard
  end

  resource :application_settings, only: [:show, :edit, :update], module: :admin

  get '/calendar', to: 'admin/application_settings#calendar'


  resources :parents, only: [:index, :create] do
    get :dashboard, on: :collection
  end

  namespace :project_attachments do
    get 'download/:id', action: :download
  end

  namespace :sessions, path: '/', as: nil do
    post :login_authentication
    get  :access_student
    get  :exit_student
    get  :login
    get  :logout
    get  :forgot_password
    post :forgot_password
  end

  get '/unfound', to: 'portfolios#unfound'
  get '/:username', to: 'portfolios#public'

end

app/controllers/klasses_controller.rb
class KlassesController < SessionsController
  load_and_authorize_resource :klass

  def index
    @highlight_sidebar = 'Dashboard'
    @klasses = Klass.search(@klasses.includes(:users, :enrolls), params)

    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    respond_to do |format|
      format.csv { send_data(@klass.to_csv, filename: "#{@klass.name}.csv") }
      format.json
    end
  end

  def new
    @highlight_sidebar = 'Dashboard'
  end

  def create
    respond_to do |format|
      if @klass.save
        format.html { redirect_to klasses_path, flash: { notice: 'Class successfully created!' } }
        format.json { render :show, status: 200 }
      else
        format.html do
          flash.now[:alert] = 'Class unsuccessfully created.'
          render :new
        end
        format.json { render json: @klass.errors, status: 422 }
      end
    end
  end

  def update
    respond_to do |format|
      if @klass.update(klass_params)
        format.html { redirect_to klasses_path, flash: { notice: 'Class successfully updated!' } }
        format.json { render :show, status: 200 }
      else
        format.html do
          flash.now[:alert] = 'Class unsuccessfully updated.'
          render :edit
        end
        format.json { render json: @klass.errors, status: 422 }
      end
    end
  end

  def edit
    @highlight_sidebar = 'Dashboard'
  end

  def destroy
    @klass.destroy
    respond_to do |format|
      format.html { redirect_to klasses_path, flash: { notice: 'Class successfully deleted.' } }
      format.json { head :no_content }
    end
  end

  private

    def klass_params
      params.require(:klass).permit(
        :name,
        :description,
        :time,
        :instructor,
        :instructor_email,
        :instructor_phone,
        :location,
        :one_on_one,
        :google_drive_url,
        :archive,
        weekdays: [],
        years: [],
        seasons: []
      )
    end

end

app/controllers/users/klasses_controller.rb
module Users
  class KlassesController < SessionsController
    load_and_authorize_resource :user
    load_and_authorize_resource :klass, through: :user, except: [:update]

    def index
      @highlight_sidebar = 'Dashboard'
      @klasses = @user.uncompleted_klasses if params[:current].present?
      @klasses = @user.completed_klasses if params[:past].present?
      @klasses = @klasses.includes(:enrolls)
    end

    def update
      @klass = Klass.find(params[:id])
      if @klass.update(klass_params)
        @klasses = @user.klasses
        render json: {}, status: 200
      else
        render json: @klass.errors, status: 422
      end
    end

    private

    def klass_params
      params.require(:klass).permit(
        :name,
        :description,
        :time,
        :instructor,
        :instructor_email,
        :instructor_phone,
        :location,
        :one_on_one,
        :google_drive_url,
        enrolls_attributes: [
          :id,
          :user_id,
          :completed,
          :_destroy
        ]
      )
    end

  end

end

app/views/klasses/_form.html.erb
<%= form_for @klass, html: { class: 'one-page' } do |f| %>

  <div class='row'>
    <div class='input-field col s12 m6'>
      <%= f.text_field :name %>
      <%= f.label :name, 'Title' %>
    </div>

    <div class='input-field col s12 m6'>
      <%= f.text_field :instructor %>
      <%= f.label :instructor %>
    </div>
  </div>

  <div class='row'>
    <div class='input-field col s12 m6'>
      <%= f.text_field :instructor_email %>
      <%= f.label :instructor_email %>
    </div>

    <div class='input-field col s12 m6'>
      <%= f.text_field :instructor_phone %>
      <%= f.label :instructor_phone %>
    </div>
  </div>

  <div class='row'>
    <div class='input-field col s12'>
      <%= f.text_area :description, class: 'materialize-textarea', value: @klass.description %>
      <%= f.label :description %>
    </div>
  </div>

  <div class='row'>
    <div class='input-field col s12 m6'>
      <%= f.select :weekdays, options_for_select(Klass::VALID_WEEKDAYS_TYPES, selected: @klass.weekdays), { include_blank: true }, { multiple: true } %>
      <%= f.label :weekday %>
    </div>

    <div class='input-field col s12 m6'>
      <%= f.text_field :time, placeholder: 'ex. 9:30AM - 11:30AM' %>
      <%= f.label :time %>
    </div>
  </div>

  <div class='row'>
    <div class='input-field col s12 m6'>
      <%= f.select :years, options_for_select(((Time.now.year - 1)..(Time.now.year + 4)), selected: @klass.years), { include_blank: true }, { multiple: true }  %>
      <%= f.label :year %>
    </div>

    <div class='input-field col s12 m6'>
      <%= f.select :seasons, options_for_select(Klass::VALID_SEASON_TYPES, selected: @klass.seasons), { include_blank: true }, { multiple: true } %>
      <%= f.label :season %>
    </div>
  </div>

  <div class='row'>
    <div class='input-field col s12 m6'>
      <%= f.url_field :google_drive_url %>
      <%= f.label :google_drive_url %>
    </div>
    <div class='input-field col s12 m6'>
      <%= f.text_field :location %>
      <%= f.label :location %>
    </div>
  </div>


  <div class='row'>
    <div class='input-field col s12'>
      <%= f.check_box :one_on_one, class: 'filled-in' %>
      <%= f.label :one_on_one, 'Tutorial' %>
    </div>
  </div>

  <div style='padding-left: 0.75rem; padding-top: 2rem;'>
    <%= content_tag :button, 'Save', type: :submit, class: 'waves-effect waves-light btn' %>
    <%= link_to 'Delete', @klass, method: :delete, data: { confirm: 'Are you positive that you want to delete this class?' },
      class: 'waves-effect waves-light btn red darken-2' unless @klass.new_record? %>
  </div>

<% end %>

app/views/klasses/edit.html.erb
<nav>
  <div class='nav-wrapper'>
    <%= link_to 'Dashboard', admin_dashboard_path, class: 'breadcrumb' %>
    <%= link_to 'Manage Classes', klasses_path, class: 'breadcrumb' %>
    <span class='breadcrumb'>Edit Class</span>
  </div>
</nav>

<section class='section-container'>
  <div class='row'>
    <h4 class='col s12'>Edit Class</h4>
  </div>

  <div class='row'>
    <%= render 'form' %>
  </div>
</section>

app/views/klasses/index.html.erb
<nav>
  <div class='nav-wrapper'>
    <%= link_to 'Dashboard', admin_dashboard_path, class: 'breadcrumb' %>
    <span class='breadcrumb'>Manage Classes</span>
  </div>
</nav>

<%= react_component 'Klasses', {} %>

app/views/klasses/new.html.erb
<nav>
  <div class='nav-wrapper'>
    <%= link_to 'Dashboard', admin_dashboard_path, class: 'breadcrumb' %>
    <%= link_to 'Manage Classes', klasses_path, class: 'breadcrumb' %>
    <span class='breadcrumb'>New Class</span>
  </div>
</nav>

<section class='section-container'>
  <div class='row'>
    <h4 class='col s12'>New Class</h4>
  </div>
  <div class='row'>
    <%= render 'form' %>
  </div>
</section>